<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Комментарии: Проведение конференций и семинаров</title>
	<atom:link href="http://terminal42.com.ua/event-service/feed/" rel="self" type="application/rss+xml" />
	<link>http://terminal42.com.ua</link>
	<description>Терминал 42. Современный коворкинг и конференц-центр в центре Одессы</description>
	<lastBuildDate>Mon, 13 Jul 2015 16:01:36 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.3.1</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.161 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-12-03 09:59:28 -->
