<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Комментарии на сайте Терминал 42</title>
	<atom:link href="http://terminal42.com.ua/comments/feed/" rel="self" type="application/rss+xml" />
	<link>http://terminal42.com.ua</link>
	<description>Терминал 42. Современный коворкинг и конференц-центр в центре Одессы</description>
	<lastBuildDate>Mon, 13 Jul 2015 16:01:36 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.3.1</generator>
	<item>
		<title>Комментарий к записи 17 июля: Алена Владимирская. Профориентация в кризис (Поговорим о мероприятиях - БлоGнот)</title>
		<link>http://terminal42.com.ua/event/alena-vl-anticrisis/#comment-13</link>
		<dc:creator><![CDATA[Поговорим о мероприятиях - БлоGнот]]></dc:creator>
		<pubDate>Mon, 13 Jul 2015 16:01:36 +0000</pubDate>
		<guid isPermaLink="false">http://terminal42.com.ua/?post_type=tribe_events&#038;p=2219#comment-13</guid>
		<description><![CDATA[[&#8230;] интернете. 17 июля у нас в Терминале 42 запланирован 6-часовой мастеркласс на тему карьеры в условиях кризи&#8230; — и я уверен в исключительной полезности этого [&#8230;]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] интернете. 17 июля у нас в Терминале 42 запланирован 6-часовой мастеркласс на тему карьеры в условиях кризи&#8230; — и я уверен в исключительной полезности этого [&#8230;]</p>
]]></content:encoded>
	</item>
	<item>
		<title>Комментарий к записи 5 июня: Феликс Шиндер и Деньги вперёд (Финалист «Голос страны 2015» Феликс Шиндер устроит квартирник в Одессе &#124; Культурометр Одессы)</title>
		<link>http://terminal42.com.ua/event/schinder5june/#comment-12</link>
		<dc:creator><![CDATA[Финалист «Голос страны 2015» Феликс Шиндер устроит квартирник в Одессе &#124; Культурометр Одессы]]></dc:creator>
		<pubDate>Mon, 01 Jun 2015 17:03:04 +0000</pubDate>
		<guid isPermaLink="false">http://terminal42.com.ua/?post_type=tribe_events&#038;p=2018#comment-12</guid>
		<description><![CDATA[[&#8230;] Послушать «короля одесского фольклора» обойдется в 150-&#8230; Концерт стартует в 20:00. [&#8230;]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] Послушать «короля одесского фольклора» обойдется в 150-&#8230; Концерт стартует в 20:00. [&#8230;]</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.181 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-12-03 14:34:34 -->
