<div class="tvd-row">
	<div class="tvd-col tvd-s12 tvd-m2">
		<h3 class="tvd-title"><?php echo __( 'Notifications', TVE_DASH_TRANSLATE_DOMAIN ) ?></h3>
	</div>
	<div class="tvd-col tvd-s12 tvd-m10">
		<a href="javascript:void(0)" id="" class="tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-nm-create-notification">
			<?php echo __( 'Add New', TVE_DASH_TRANSLATE_DOMAIN ) ?>
		</a>
	</div>
</div>

<div id="tvd-nm-notifications-list"></div>
